"""
Stage 8 — Distribution

Publishes approved clips to social media platforms via direct API calls.
Each platform has its own upload function. The clip's metadata JSON provides
the title, caption, and hashtags generated by the AI Scoring stage.

Platforms (implemented progressively as API access is set up):
  - YouTube Shorts   — YouTube Data API v3
  - TikTok           — TikTok Content Posting API
  - Instagram Reels  — Meta Graph API
  - Twitter/X        — Twitter API v2 (media upload + tweet)
  - Reddit           — Reddit API (PRAW)

Distribution result (success/failure per platform) is appended to the clip's
.meta.json under a 'distribution' key for tracking in the Optimize stage.
"""

from utils.logger import get_logger

logger = get_logger(__name__)


def run_distribution(clip_path: str, metadata: dict, config: dict) -> dict:
    """Publish an approved clip to all configured platform targets.

    Args:
        clip_path: Path to the approved clip in accepted/{game}/.
        metadata: Full clip metadata dict including scoring results and template info.
        config: Full parsed config.yaml dict.

    Returns:
        Dict mapping platform name → result dict (success bool, url or error message).
    """
    pass
